### ISSUE TITLE
Great content!

### ISSUE THREAD

**Issue by codeitch** [explorer953/explorer953.github.io#1]
I would just like to ask if you are aware of any hints for enumerating Reply URL types with "lower" permissions (e.g. directory.read.all, etc.)?

**Comment by explorer953** [comment]
For what I understood, permissions depend on the Application itself and not in the reply URL, so if an application has many reply URLs defined, they all will share the same permissions.

When it comes to enumeration, you can try to request this scope in the first stage of the flow, if the flow completes and returns tokens, then the app is configured to delegate this permission.
